services:
  arwoh.api:
    image: arwoh.api
    build:
      context: .
      dockerfile: ArWoh.API/Dockerfile
    ports:
      - "9090:8080"
      - "9091:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080;http://+:8081"
      ConnectionStrings__DefaultConnection: "Server=103.211.201.162,1433;Database=ArWohDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True"
      JWT__SecretKey: "YourSuperStrongJWTSecretKeyWithAtLeast32Chars"
      JWT__Issuer: "ArWoh"
      JWT__Audience: "ArWohUsers"
      MINIO_ENDPOINT: "minio.ae-tao-fullstack-api.site:9000"
      MINIO_ACCESS_KEY: "103.211.201.162"
      MINIO_SECRET_KEY: "Ccubin2003@"
    depends_on:
      - arwoh.db

  arwoh.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: arwoh.db
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local
